version: "3.9"
services:

  database:
    image: neo4j
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    # USED FOR DATA PERMANENCE
    # volumes:
    #   - $NEO4J_DATA:/data
    #   - $NEO4J_LOG:/logs
    environment:
      - NEO4J_AUTH=neo4j/2007flex
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # - NEO4J_URI=bolt://localhost:7687
    networks:
      - mynetwork

  web:
      image: "capstone-heroes-docker"
      ports:
        - "8080:8080"
      links:
        - "database:database"
      networks:
        - mynetwork

networks:
  mynetwork:
    driver: bridge

